# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xlbYQXchZ85wZpQDuFC9LUDs8FzhthFz
"""

name = input("What is your name? ")
age = input("How old are you? ")
hobby = input("What is your hobby? ")

print("\n🎉 Welcome", name, "! 🎉")
print("You are", age, "years old and you love", hobby)
